ALTER TABLE "Client" ADD COLUMN "street" TEXT;
ALTER TABLE "Client" ADD COLUMN "number" TEXT;
ALTER TABLE "Client" ADD COLUMN "neighborhood" TEXT;
ALTER TABLE "Client" ADD COLUMN "city" TEXT;
ALTER TABLE "Client" ADD COLUMN "state" TEXT;
ALTER TABLE "Client" ADD COLUMN "zipCode" TEXT;
